lidar:
  ros__parameters:
    frame_id: "base_scan"
    range_max: 5.0
    angle_min: -3.14159  # -π radians
    angle_max: 3.14159   # π radians
    angle_increment: 0.0157  # 0.9 degrees in radians
    scan_time: 0.033
    range_min: 0.1
    range_max: 5.0
